### PR TITLE
Repository layout changes, prepare info for building PCB layout

### PR DESCRIPTION
**Pull request by quorten**
So, not only did I go through the repository to make changes to the organization to make it more similar to other KiCad hardware project repos, but I also built out some structures that at the current moment, might be too audacious of a goal.  But why not?  It seems to make sense, and a lot of the related vintage Macintosh projects are out there to assemble bits and pieces of this bigger picture.  Let me know your thoughts on the over-designed repository structure for additional directions this project could go in.  If you think it's too much over-designing, we can trim down the unused directory layout and add it back later.

Also, I've added some links and download scripts to information that will help me put together a printed circuit board layout.  A PCB layout that supports creating an interactive Bill of Materials (BOM) should be easy to piece together, I've also dropped in a link to another recap info page for my reference when doing so.

### CODE REVIEW

**Comment by quorten** [comment]
The `firmware` directory structure may be useful even if we just end up adding links to other projects.  ROM-inator II is a prime project to consider making reference to, for example.

**Comment by quorten** [comment]
One thing that we want to avoid is committing ZIP files to the repository.  I've unzipped the KiCad schematic files when reorganizing.  Another thing is that we want to avoid special characters in file names when it makes sense, and avoid long file names when it makes sense.  These are mostly conventions made with software source code in general, and by extension, hardware design sources.

**Comment by mishimasensei** [comment]
Thanks for doing this. I'm new to GitHub so want to make sure I merge correctly. I just made some other changes for problems a forum member caught. What should I do at this point to properly merge in your changes?

**Comment by quorten** [comment]
In Git, when this happens, typically folks with pull requests out like me will pull the latest master branch and work out resolving merge conflicts on our side, then we will push the updates.  Yeah, so that's on me to do that.  I work with using Git CLI commands to do this, it should be easy to update my branch with the updates from master since I've only rearranged files.

**Comment by quorten** [comment]
What is your opinion on my changes?  Do you think there should be the additional directory structures for 3d_prints, firmware, etc. in the repository, or just stick with a layout based off of the main project that is pretty much completed in this repo?

**Comment by mishimasensei** [comment]
I think it's nice to be so thorough to accommodate extra bits if people want to contribute to them.

**Comment by quorten** [comment]
Alright, I've pulled in the updates from the master branch and fixed the merge conflicts.  If you think these changes look good, go ahead and merge when you are ready.

**Comment by mishimasensei** [comment]
merged. only issue I see is that it's not clear where the PDFs would be. is 'output' typical nomenclature for that sort of thing?

**Comment by quorten** [comment]
Good point, actually in this case it's not typical nomenclature.  I'm still trying to figure out what is the best way to include generated files in a repository.  Software projects typically don't include them because they are easy to generate from scripts, but hardware projects have various justified reasons for including generated files in the repository.

I'll add a note to the READMEs about this.

**Pull request merged**
